services:
- type: web
  name: myresumo
  runtime: python
  repo: https://github.com/AnalyticAce/MyResumo
  plan: free
  envVars:
  - key: OCTO_AI_TOKEN
    sync: false
  - key: TESSDATA_PREFIX
    value: ./tessdata
  region: frankfurt
  buildCommand: |
    pip install -r requirements.txt
    pip install openai==0.28
    pip install pytesseract==0.3.10
  startCommand: streamlit run streamlit_app.py
version: "1"
