// PowerCV integration for RenderCV Classic template
#import "@preview/rendercv:0.1.0": *

// Apply the rendercv template with classic configuration
#show: rendercv.with(
  name: data.user_information.name,
  footer: context { [#emph[data.user_information.name -- #str(here().page())\/#str(counter(page).final().first())]] },
  top-note: [ #emph[Generated by PowerCV] ],
  locale-catalog-language: "en",
  page-size: "us-letter",
  page-top-margin: 0.7in,
  page-bottom-margin: 0.7in,
  page-left-margin: 0.7in,
  page-right-margin: 0.7in,
  page-show-footer: true,
  page-show-top-note: true,
  colors-body: rgb(0, 0, 0),
  colors-name: rgb(0, 79, 144),
  colors-headline: rgb(0, 79, 144),
  colors-connections: rgb(0, 79, 144),
  colors-section-titles: rgb(0, 79, 144),
  colors-links: rgb(0, 79, 144),
  colors-footer: rgb(128, 128, 128),
  colors-top-note: rgb(128, 128, 128),
  typography-line-spacing: 0.6em,
  typography-alignment: "justified",
  typography-date-and-location-column-alignment: right,
  typography-font-family-body: "Source Sans 3",
  typography-font-family-name: "Source Sans 3",
  typography-font-family-headline: "Source Sans 3",
  typography-font-family-connections: "Source Sans 3",
  typography-font-family-section-titles: "Source Sans 3",
  typography-font-size-body: 10pt,
  typography-font-size-name: 30pt,
  typography-font-size-headline: 10pt,
  typography-font-size-connections: 10pt,
  typography-font-size-section-titles: 1.4em,
  typography-small-caps-name: false,
  typography-small-caps-headline: false,
  typography-small-caps-connections: false,
  typography-small-caps-section-titles: false,
  typography-bold-name: true,
  typography-bold-headline: false,
  typography-bold-connections: false,
  typography-bold-section-titles: true,
  links-underline: false,
  links-show-external-link-icon: false,
  header-alignment: center,
  header-photo-width: 3.5cm,
  header-space-below-name: 0.7cm,
  header-space-below-headline: 0.7cm,
  header-space-below-connections: 0.7cm,
  header-connections-separator: "",
  header-connections-space-between-connections: 0.5cm,
  header-connections-show-icons: true,
  section-titles-type: "with_full_line",
  section-titles-line-thickness: 0.5pt,
  section-titles-space-above: 0.5cm,
  section-titles-space-below: 0.3cm,
  sections-allow-page-break: true,
  sections-space-between-text-based-entries: 0.3em,
  sections-space-between-regular-entries: 1.2em,
  entries-date-and-location-width: 4.15cm,
  entries-side-space: 0.2cm,
  entries-space-between-columns: 0.1cm,
  entries-allow-page-break: false,
  entries-summary-space-left: 0cm,
  entries-summary-space-above: 0.12cm,
  entries-highlights-bullet: "■",
  entries-highlights-nested-bullet: "▪",
  entries-highlights-space-left: 0cm,
  entries-highlights-space-above: 0.12cm,
  entries-highlights-space-between-items: 0.12cm,
  entries-highlights-space-between-bullet-and-text: 0.5em,
)

= data.user_information.name

#headline([data.user_information.main_job_title])

#connections(
  if data.user_information.address != none and data.user_information.address != "" {
    [#connection-with-icon("location-dot")[data.user_information.address]]
  },
  if data.user_information.email != none and data.user_information.email != "" {
    [#link("mailto:" + data.user_information.email, icon: false, if-underline: false, if-color: false)[#connection-with-icon("envelope")[data.user_information.email]]]
  },
  if data.user_information.phone != none and data.user_information.phone != "" {
    [#connection-with-icon("phone")[data.user_information.phone]]
  },
  if data.user_information.linkedin != none and data.user_information.linkedin != "" {
    [#link("https://" + data.user_information.linkedin, icon: false, if-underline: false, if-color: false)[#connection-with-icon("linkedin")[data.user_information.linkedin]]]
  },
  if data.user_information.github != none and data.user_information.github != "" {
    [#link("https://" + data.user_information.github, icon: false, if-underline: false, if-color: false)[#connection-with-icon("github")[data.user_information.github]]]
  },
  if data.user_information.homepage != none and data.user_information.homepage != "" {
    [#link(data.user_information.homepage, icon: false, if-underline: false, if-color: false)[#connection-with-icon("globe")[data.user_information.homepage]]]
  },
)

== Professional Experience

#for experience in data.experiences {
  let start_date = experience.start_date
  let end_date = if experience.end_date != "" { experience.end_date } else { "Present" }
  let date_range = start_date + " – " + end_date

  regular-entry(
    [
      #strong[experience.job_title], experience.company
      #if experience.location != "" { [ – experience.location] }
    ],
    [
      experience.location

      date_range
    ],
    main-column-second-row: [
      #for desc in experience.description.split("\n").filter(item => item != "") {
        [- desc]
      }
    ],
  )
}

== Education

#for education in data.education {
  education-entry(
    [
      #strong[education.institution], education.field_of_study
    ],
    [
      education.location

      education.graduation_date
    ],
    degree-column: [
      #strong[education.degree]
    ],
    main-column-second-row: [
      #for desc in education.description.split("\n").filter(item => item != "") {
        [- desc]
      }
    ],
  )
}

== Skills

#regular-entry(
  [
    #strong[Technical Skills]
  ],
  [],
  main-column-second-row: [
    #for skill in data.skills {
      [- #strong[skill.name]: skill.proficiency]
    }
  ],
)

#for project in data.projects {
  regular-entry(
    [
      #strong[project.name], project.organization
    ],
    [
      project.location

      project.start_date + if project.end_date != "" { " – " + project.end_date } else { " – Present" }
    ],
    main-column-second-row: [
      #for desc in project.description.split("\n").filter(item => item != "") {
        [- desc]
      }
    ],
  )
}

#for cert in data.certifications {
  regular-entry(
    [
      #strong[cert.name], cert.issuer
    ],
    [
      cert.issue_date + if cert.expiry_date != "" { " – " + cert.expiry_date } else { "" }
    ],
    main-column-second-row: [
      #for desc in cert.description.split("\n").filter(item => item != "") {
        [- desc]
      }
    ],
  )
}