name: Docker Image CI/CD for GHCR

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/publish-ghcr.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/publish-ghcr.yml'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx (for caching)
        uses: docker/setup-buildx-action@v2

      - name: Build and push with caching
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/analyticace/myresumo:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max